### ISSUE TITLE
In Debug Mode...

### ISSUE THREAD

**Issue by kxygk** [flathub/io.github.jkozera.ZevDocs#1]
Application launches in Debug mode...

Getting a 

```
Waiting for zealcore...
[GIN-debug] [WARNING] Running in  "debug" mode. Switch to "release" mode in production
```

**Comment by jmymay** [comment]
Thanks for the report! It's now fixed with  jkozera/zevdocs@24e705ed241087339dc09aa4434c4575bc89bf2a.
